### ISSUE TITLE
用語集を作る

### ISSUE THREAD

**Issue by akiRAM3** [yomogimochi-karaage/kara_age#12]
今後仕様が大きく動く事はなさそう＆思ったよりゲーム内の要素が多くなってきたので、
ここで早めに用語の統一をしたいと思います。
メンバー間の会話の中で齟齬が発生するのを防止する目的です。

基本的にはTaipuiさんに作って頂いたクラス集に定義されたものをベースにしていこうと思います。
|  統一後  |  表記ブレ例/説明  |
| ---- | ---- |
|  プレイヤー  |  天使, 自キャラ  |
|  HP  |  体力, 残機  |
|  エナジー(EnergyItem)  |  オーブ, エネルギーオーブ, アイテム  |
|  攻撃  |  通常攻撃, 貯めじゃない攻撃  |
|  ため攻撃  |  壁破壊攻撃, 強攻撃  |
|  メリケン  |  (ため攻撃の単位)  |
|  1敵(Enemy)  |  悪魔, オバケ, 1発で倒せる敵キャラ  |
|  2敵  |  倒すのに2発必要な敵キャラ  |
|  壁敵(NuisanceEnemy)  |  倒した時壁に変化する敵キャラ  |
|  闇敵(BlindEnemy)  |  食らうと視界が制限される攻撃を繰り出す敵キャラ  |
|  スコア  |  得点,点数  |
|  ダンジョン  |  迷路, マップ  |
|  祭壇  |  (プレイヤーのHPが回復出来る場所)  |
|  壁  |  通常の壁, 爆弾付きでない壁  |
|  爆弾壁 |  (爆弾付きの壁)  |
|  ゴール | 扉, 階段  |

**Comment by ChameleonO2** [comment]
用語集、当リポジトリのWikiにも転記しておきました

**Comment by akiRAM3** [comment]
wiki管理のほうがよさそうなので、こっちはCloseします
