### ISSUE TITLE
スコア算出式

### ISSUE THREAD

**Issue by Kanon04** [yomogimochi-karaage/kara_age#18]

**Comment by akiRAM3** [comment]
補足
スコアの点数の計算式を決定する

例）
　ステージ階層 * 1000点
　壁破壊 * 100点
　敵倒す * 25点
など

※敵を倒すより壁破壊のインセンティブが多いこと

**Comment by N-JELLY** [comment]
あきらむさんの例の通りに実装お願いします

**Comment by Taipui** [comment]
対応しました。
