### ISSUE TITLE
[プロトタイプ]プレイヤーのグラフィックの表示がおかしい

### ISSUE THREAD

**Issue by akiRAM3** [yomogimochi-karaage/kara_age#21]
![image](https://user-images.githubusercontent.com/109776586/188905361-e94dd4a7-79e8-44bb-907d-6c01337e8f20.png)
待機アニメの2枚中1枚、天使の顔が向いてるほうに若干白いピクセルが表示されてる？
解像度が違うか、アトラス化の時にずれたかも？

**Comment by akiRAM3** [comment]
なんか全体的に表示がボヤけてる気がする

**Comment by yomogi-mochi-neos** [comment]
![image](https://user-images.githubusercontent.com/106639014/188911377-9e3bf38a-70cd-4e78-ba55-946970fd5f7d.png)
対応済み
