### ISSUE TITLE
全画面表示にするとUIが崩れる

### ISSUE THREAD

**Issue by N-JELLY** [yomogimochi-karaage/kara_age#26]
理想を言えば左右に広がった分黒く塗りつぶしてほしい

**Comment by N-JELLY** [comment]
![image](https://user-images.githubusercontent.com/85563249/188910881-cd4f0715-7730-4707-b35f-fabba937eb4d.png)

**Comment by yomogi-mochi-neos** [comment]
UnityRoomだと、フルスクリーンモード無いなぁって（小声）

**Comment by N-JELLY** [comment]
UnityRoomにフルスクリーンモード無いとの事なので対応しなくて大丈夫です
