### ISSUE TITLE
初期生成のマップに閉じ込められて詰んじゃう

### ISSUE THREAD

**Issue by SLAVR00** [yomogimochi-karaage/kara_age#33]
- 症状
    - 初期生成の状態で道がふさがって閉じ込められる
- 考えられる原因
    - 扉の生成時に重なって塞がれる?

![f1309d7d8a24ee2bcd8091394fe53808](https://user-images.githubusercontent.com/103572086/188938538-3ca55d70-447d-40ae-af07-9e5ea7b715c0.png)

**Comment by yomogi-mochi-neos** [comment]
直しました！！！！！
