### ISSUE TITLE
ミニマップ上で通常壁と爆弾壁の色を変える

### ISSUE THREAD

**Issue by N-JELLY** [yomogimochi-karaage/kara_age#40]

**Comment by yomogi-mochi-neos** [comment]
具体的な色の指定も頂けると嬉しいです！

**Comment by N-JELLY** [comment]
通常壁は今まで通り透過で、爆弾壁は#A6A600でお願いします

**Comment by yomogi-mochi-neos** [comment]
![image](https://user-images.githubusercontent.com/106639014/189038182-e4bf8b28-6e67-4873-b89e-25a998305911.png)
こんなかんじになりました

**Comment by yomogi-mochi-neos** [comment]
（アイテムの色と被らないかな。。）

**Comment by N-JELLY** [comment]
被るかも...
後通常壁は透明で今まで通り通路が白のイメージでした

**Comment by yomogi-mochi-neos** [comment]
アイテム色を緑色に変更しました
